### Multiplying matrices and basic linear algebra

In [1]:
import numpy as np
from numpy.random import randn

In [2]:
np.printoptions(precision=2)

#### Multiplying matrices

In [3]:
a1 = np.array([[2,4,6],[1,3,5],[10,20,30]])
a1

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [10, 20, 30]])

In [4]:
a2 = np.array([[0,1,2],[3,4,5],[6,7,8]])
a2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
a1*a2

array([[  0,   4,  12],
       [  3,  12,  25],
       [ 60, 140, 240]])

#### Basic linear algebra

Using the `dot` method (_dot product_) we are multiplying matrices but this time by row and col. So in our example :-
2*0 + 4*3 + 6*6 = 48 (row 1 of a1 and col 1 of a2) and so on ....

In [6]:
np.dot(a1,a2)

array([[ 48,  60,  72],
       [ 39,  48,  57],
       [240, 300, 360]])