### Simple Arithmetic operations on data using NumPy

In [12]:
import numpy as np
from numpy.random import randn

np.printoptions(precision=2)

#### Creating Arrays
Creating arrays with a list

In [5]:
a1 = np.array([1,2,3,4,5,6])
a1

array([1, 2, 3, 4, 5, 6])

In [7]:
m1 = np.array([[10,20,30],[40,50,60]])
m1

array([[10, 20, 30],
       [40, 50, 60]])

Creating an array with _assignment_

In [13]:
np.random.seed(25)
a2 = 36*np.random.randn(6)
a2

array([  8.21783123,  36.96805091, -30.22505456, -21.28253464,
       -34.44797868,  -8.003725  ])

In [9]:
a3 = np.arange(1, 35)
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

#### Performing arithmatic on arrays

In [10]:
a1*10

array([10, 20, 30, 40, 50, 60])

In [14]:
a1 + a2

array([  9.21783123,  38.96805091, -27.22505456, -17.28253464,
       -29.44797868,  -2.003725  ])

In [15]:
a2 * a1

array([   8.21783123,   73.93610183,  -90.67516369,  -85.13013858,
       -172.2398934 ,  -48.02234998])